export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const GET_CURRENT_USER_DETAILS = 'GET_CURRENT_USER_DETAILS';
export const CREATE_TEAM = 'CREATE_TEAM';
export const SELECT_TEAM = 'SELECT_TEAM';
export const GET_TEAM_DATA = 'GET_TEAM_DATA';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
export const RESET_SINGLE_EVENT = 'RESET_SINGLE_EVENT';
export const ADD_ATTENDANCE_RESPONSE = 'ADD_ATTENDANCE_RESPONSE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const GET_ALL_ATTENDEES = 'GET_ALL_ATTENDEES';
export const GET_MEMEBRS = 'GET_MEMEBRS';
export const GET_MEMORIES = 'GET_MEMORIES';
export const LISTEN_TO_EVENT_CHAT = 'LISTEN_TO_EVENT_CHAT';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';